[package]
name = "lily58-hid-controller"
version = "0.1.0"
authors = ["Dave Allie <dave@daveallie.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "1.2.*"
chrono = "*"
